-- 1. Crear tabla de clientes
CREATE TABLE clientes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pedido TEXT,
  nombre TEXT NOT NULL,
  telefono TEXT,
  email TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. Crear tabla de licencias
CREATE TABLE licencias (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cliente_id BIGINT REFERENCES clientes(id) ON DELETE CASCADE,
  tipo TEXT NOT NULL,
  detalle TEXT NOT NULL, -- Aquí se guardará el texto cifrado (AES-GCM Base64)
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 3. Habilitar Row Level Security (RLS)
ALTER TABLE clientes ENABLE ROW LEVEL SECURITY;
ALTER TABLE licencias ENABLE ROW LEVEL SECURITY;

-- 4. Crear políticas de seguridad (Sólo usuarios autenticados pueden ver, insertar, actualizar y borrar)

-- Políticas para clientes
CREATE POLICY "Permitir select a usuarios autenticados" ON clientes FOR SELECT TO authenticated USING (true);
CREATE POLICY "Permitir insert a usuarios autenticados" ON clientes FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Permitir update a usuarios autenticados" ON clientes FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Permitir delete a usuarios autenticados" ON clientes FOR DELETE TO authenticated USING (true);

-- Políticas para licencias
CREATE POLICY "Permitir select a usuarios autenticados" ON licencias FOR SELECT TO authenticated USING (true);
CREATE POLICY "Permitir insert a usuarios autenticados" ON licencias FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Permitir update a usuarios autenticados" ON licencias FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Permitir delete a usuarios autenticados" ON licencias FOR DELETE TO authenticated USING (true);
